# lightning.pytorch==2.0.6
seed_everything: 1337
trainer:
  accelerator: gpu
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: 32-true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: null
      save_dir: .
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: journal2_extension
      log_model: false
      experiment: null
      prefix: ''
      checkpoint_name: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 100
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  log_every_n_steps: 100
  enable_checkpointing: null
  enable_progress_bar: true
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: 5.0
  gradient_clip_algorithm: null
  deterministic: false
  benchmark: true
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: /home/marvint/dr/code/deep_learning_projects/journal2_extension/bmfwf/saved/20240712_182530_fluffy-term-49
compile: false
checkpoint: null
job_type: fit
ckpt_path: /home/marvint/dr/code/deep_learning_projects/journal2_extension/bmfwf/saved/20240712_182530_fluffy-term-49/last.ckpt
model:
  class_path: bmfwf.models.BDMFMVDR
  init_args:
    learning_rate: 0.001
    batch_size: 8
    loss: MagnitudeAbsoluteError
    metrics_test: HASQI,HASPI,PESQWB,SISDR
    metrics_val: ''
    frame_length: 128
    shift_length: 32
    filter_length: 5
    layer: 6
    stack: 2
    kernel: 3
    hidden_dim: null
    num_channels: 2
    reg: 0.001
    fixed_time_constant_noisy: null
    fixed_time_constant_noise: null
    min_time_constant_noisy: null
    min_time_constant_noise: null
    minimum_gain: -20.0
    minimum_gain_k: 10.0
    window_type: hann
    minimum_gain_implementation: conventional
    matrix_structure: hermitian_psd
    speech_ifc_estimation: direct
    mode: spatio_temporal
    feature_representation: mag_phase
    use_mwf: true
    explicit_rank1: true
    compute_inverse: false
    use_batchnorm: true
    use_log: true
    oracle: false
    time_invariant: false
    interaural_rtf: 'False'
    binaural: true
    shadow_filter: false
    hermitian_psd_old_implementation: false
    hermitian_psd_unique: true
    omit_first_last_bin: true
    normalize_gamma: false
    noise_stcm_left_and_right: false
    estimator: tcn
    D: 32
    E: 8
    I: 8
    J: 4
    Q: null
    H: 256
    E_prime: 64
    I_prime: 5
    J_prime: 5
    Q_prime: null
    H_prime: 64
    B: 3
    fix_omit_first_last_bin: true
data:
  class_path: bmfwf.datasets.DataModuleDNSBinaural
  init_args:
    train_split: 0.8
    dataset_version: v2
    limit_train_val_size: 1.0
    snr_train_min: 0.0
    snr_train_max: 15.0
    snr_test: -5 0 5 10 15 20
    num_workers: 8
    data_dirs:
      clean: /data1/DNS3/DNS-Challenge/datasets/dns3_bte_ir_100/clean
      noise: /data1/DNS3/DNS-Challenge/datasets/dns3_bte_ir_100/noise
      noisy: /data1/DNS3/DNS-Challenge/datasets/dns3_bte_ir_100/noisy
      meta: /data1/DNS3/DNS-Challenge/datasets/dns3_bte_ir_100/meta
    fs: 16000
    target: clean
    target_eval: clean
    inp: noisy
    num_channels: 2
    use_binaural_references: true
